### ISSUE TITLE
ImageLocation must be set error

### ISSUE THREAD

**Issue by BaconDave312** [ic3w0lf22/Roblox-Account-Manager#344]
Unhandled exception has occurred in your application. If you click
Continue, the application will ignore this error and attempt to continue. f
you click Quit, the application will close immediately.
ImageLocation must be set.
![image](https://github.com/ic3w0lf22/Roblox-Account-Manager/assets/120328764/95cd3167-a014-4030-896e-34afc4daa350)
that happens when i try searching for avatars (it also only shows stevie standard)

**Comment by BaconDave312** [comment]
(i dont have a jit debugger)

**Comment by MarcusM2092** [comment]
im having the same issue and it says this "See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at RBX_Alt_Manager.AccountManager.AccountsView_Scroll(Object sender, ScrollEventArgs e) in C:\Users\Euonix\source\repos\RBX Alt Manager\RBX Alt Manager\AccountManager.cs:line 2141
   at BrightIdeasSoftware.ObjectListView.OnScroll(ScrollEventArgs e)
   at BrightIdeasSoftware.ObjectListView.HandleBeginScroll(Message& m)
   at BrightIdeasSoftware.ObjectListView.HandleReflectNotify(Message& m)
   at BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Roblox Account Manager
    Assembly Version: 1.0.0.0
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9236.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
log4net
    Assembly Version: 2.0.15.0
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.2
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.1072
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
RestSharp
    Assembly Version: 110.2.0.0
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Text.Json
    Assembly Version: 7.0.0.2
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
System.Threading.Tasks.Extensions
    Assembly Version: 4.2.0.1
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
FastColoredTextBox
    Assembly Version: 2.16.24.0
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
PuppeteerSharp
    Assembly Version: 10.0.0.0
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9232.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 7.0.0.0
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
Yove.Proxy
    Assembly Version: 1.1.1.0
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
PuppeteerExtraSharp
    Assembly Version: 1.3.1.0
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
websocket-sharp
    Assembly Version: 1.0.1.0
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 7.0.0.0
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 7.0.0.0
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 7.0.0.1
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
System.Buffers
    Assembly Version: 4.0.3.0
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
System.Net.Http.Json
    Assembly Version: 7.0.0.1
    Win32 Version: 3.6.1.0
    CodeBase: file:///C:/Users/Marcus/Desktop/Roblox%20Account%20Manager/Roblox%20Account%20Manager.exe
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


"
